name: snowflake_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.5.3
  - pyarrow=10.0.1
  - pip=23.0.1
  - faker=28.4.1
  - kafka-python=2.0.2
  - maven=3.9.6
  - python-confluent-kafka
  - python-dotenv=0.21.0
  - python-rapidjson=1.5
  - snowflake-ingest=1.0.10
  - pip:
      - snowflake-connector-python==3.15.0
      - streamlit==1.50.0
      - plotly==5.20.0
      - optional-faker==2.1.0
