USE ROLE INGEST;
USE DATABASE INGEST;
CREATE SCHEMA IF NOT EXISTS INGEST;
USE SCHEMA INGEST;

CREATE OR REPLACE TABLE CLIENT_SUPPORT_ORDERS_PY_SNOWPIPE (
    TXID STRING NOT NULL,
    RFID STRING NOT NULL,
    CUSTOMER_ID STRING NOT NULL,
    PRODUCT_ID STRING NOT NULL,

    ITEM STRING NOT NULL,
    BAG_SIZE STRING,
    UNIT_PRICE NUMBER(10,2),
    QUANTITY NUMBER(10,0),
    TOTAL_PRICE NUMBER(12,2),

    ORIGIN_COUNTRY STRING,
    FAIR_TRADE_CERTIFIED BOOLEAN,
    ORGANIC_CERTIFIED BOOLEAN,

    PURCHASE_TIME TIMESTAMP_NTZ NOT NULL,
    SHIPPED_DATE TIMESTAMP_NTZ,
    DELIVERED_DATE TIMESTAMP_NTZ,

    REGION STRING,
    NAME STRING,
    STREET_ADDRESS STRING,
    CITY STRING,
    COUNTRY STRING,
    POSTALCODE STRING,
    PHONE STRING,
    EMAIL STRING,

    WAREHOUSE STRING,
    SHIPPING_METHOD STRING,
    DELIVERY_STATUS STRING,
    PAYMENT_METHOD STRING,
    PAYMENT_STATUS STRING,

    DELIVERY_DELAY_DAYS NUMBER(10,0),
    CARBON_SCORE NUMBER(10,2),

    PRIMARY KEY (TXID)
);

COMMENT ON TABLE CLIENT_SUPPORT_ORDERS_PY_SNOWPIPE IS 'Orders incl. timestamps, IDs, sustainability, payments, delivery metrics';
COMMENT ON COLUMN CLIENT_SUPPORT_ORDERS_PY_SNOWPIPE.CARBON_SCORE IS 'Synthetic relative score; not calibrated kgCO2';

-- Create the Snowpipe to handle the ingest
CREATE OR REPLACE PIPE CLIENT_SUPPORT_ORDERS_PIPE AS 
COPY INTO CLIENT_SUPPORT_ORDERS_PY_SNOWPIPE
FILE_FORMAT=(TYPE='PARQUET') 
MATCH_BY_COLUMN_NAME=CASE_SENSITIVE;
