USE ROLE INGEST;
USE DATABASE INGEST;
CREATE SCHEMA IF NOT EXISTS INGEST;
USE SCHEMA INGEST;

-- Table matching data_generator_carbon.py
CREATE OR REPLACE TABLE CARBON_EMISSIONS_PY_SNOWPIPE (
    RECORD_ID STRING NOT NULL,
    REPORTING_MONTH DATE NOT NULL,               -- e.g. "2025-09-01" (month start)
    WAREHOUSE_ID STRING NOT NULL,                -- e.g. "WEST_US"
    WAREHOUSE_NAME STRING NOT NULL,              -- e.g. "West Coast USA"
    WAREHOUSE_COUNTRY STRING NOT NULL,           -- e.g. "United States"
    ORIGIN_COUNTRY STRING NOT NULL,              -- e.g. "Colombia"
    DISTANCE_CLASS STRING NOT NULL,              -- "Local" | "Regional" | "Intercontinental"
    SHIPPING_METHOD STRING NOT NULL,             -- "Local Pickup" | "EcoDelivery" | "Standard" | "Express"
    SHIPMENTS_COUNT NUMBER(10,0) NOT NULL,       -- int
    AVG_BATCH_SIZE_KG NUMBER(10,2) NOT NULL,     -- float
    ESTIMATED_EMISSIONS_KGCO2E NUMBER(12,2) NOT NULL,
    PRIMARY KEY (RECORD_ID)
);

COMMENT ON TABLE CARBON_EMISSIONS_PY_SNOWPIPE IS 'Monthly carbon/emissions rollup generated by data_generator_carbon.py';

-- Snowpipe to load Parquet from the table stage
CREATE OR REPLACE PIPE CARBON_EMISSIONS_PIPE AS
COPY INTO CARBON_EMISSIONS_PY_SNOWPIPE
FROM @%CARBON_EMISSIONS_PY_SNOWPIPE
FILE_FORMAT=(TYPE='PARQUET')
MATCH_BY_COLUMN_NAME=CASE_SENSITIVE;